### ISSUE TITLE
The chapter 8 code does not render

### ISSUE THREAD

**Issue by jrobm2k9** [EvanHahn/Express.js-in-Action-code#14]
I have copied the code exactly as it is listed in github, but I get this error everytime: 

```SyntaxError: Unexpected identifier in /app/views/index.ejs while compiling ejs```

I think the issue is with the include statements, I don't think they're in the correct format, but I couldn't figure out what they should be based off the ejs docs.  If I remove the include for the header and footer and copy the contents of _header and _footer into index.ejs, I get the following error:

```ReferenceError: /app/views/index.ejs:34
    32|     
    33|     <div class="container">
 >> 34|       <% errors.forEach(function(error){ %>
    35|         <div class="alert alert-danger" role="alert">
    36|           <%= error %>
    37|         </div>

errors is not defined
```
What does error reference?  When I looked at the routes, I didn't see where error was defined, can you help?

**Comment by EvanHahn** [comment]
`errors` comes from [this line](https://github.com/EvanHahn/Express.js-in-Action-code/blob/master/Chapter_08/learn-about-me/routes.js#L18), I believe.

Does that help? If not, I can help dig into this further.

**Comment by jrobm2k9** [comment]
Yes it did, thanks.  On another note, _header and _footer won't render and still produced the error:
```SyntaxError: Unexpected identifier in /app/views/index.ejs while compiling ejs```
I had to change the include statement in index.ejs, signup.ejs, login.ejs, edit.ejs, and profile.ejs to this:
```<%- include('_header') %>``` and ```<%- include('_footer') %>```
I'm using ejs 3.0.1.

**Comment by EvanHahn** [comment]
At a high level, a lot of the stuff in the book is already out of date, which you may be running into as you work.

If your immediate issue has been solved, would you mind closing? No problem if not, feel free to leave it open.

**Comment by EvanHahn** [comment]
This issue has been open for over a year so I'm going to close.
