### ISSUE TITLE
isModified("password" ) return true if it is modified.

### ISSUE THREAD

**Issue by MURHAF-ELMASRI** [EvanHahn/Express.js-in-Action-code#15]
--------------------------------
from mongooes doc :
-------------------------------------
Document.prototype.isModified()
Parameters
[path] «String» optional
Returns:
«Boolean»
Returns true if any of the given paths is modified, else false. If no arguments, returns true if any path in this document is modified.
<hr>
So how could the below function return true if we set the password for the first time.

`(!user.isModified("password"))

**Comment by EvanHahn** [comment]
Not sure. Is it possible that the book is using an outdated version of Mongoose?
