### ISSUE TITLE
syntax of include for ejs has changed - Chapter 3 index.ejs is affected

### ISSUE THREAD

**Issue by JamesCHub** [EvanHahn/Express.js-in-Action-code#16]
for the includes in index.ejs and new-entry.ejs in Chapter 3, 
change from:
 <% include header %> 
to
 <%- include('header'); %>

and likewise for footer

where:
"ejs": "^3.1.6",
"express": "^4.17.1",

**Comment by EvanHahn** [comment]
It looks like you've run into a spot where the book is using an out-of-date EJS version.

If the code in the book is incorrect with the old EJS version, let me know and I'll update the errata. Otherwise, I'm going to close this issue.
