### ISSUE TITLE
Erratum on page 175

### ISSUE THREAD

**Issue by amandeepmittal** [EvanHahn/Express.js-in-Action-code#2]
The screenshot describing use of JSHINT in a text editor, specified "Sublime Text Editior" is not actually Sublime Text but Atom Editor if looked carefully on the logo adjacent to file name on title bar of text editor.

**Comment by EvanHahn** [comment]
Turns out it _is_ Sublime but I'd set Atom as the default app for opening `.js` files, so OS X changed the icon.

This is still something I should fix, though! I'll add it to my list of errata.

**Comment by amandeepmittal** [comment]
Oh okay. By the look of the logo it appeared to be Atom. However, thanks for such a great insight of Expressjs. Looking forward to more of your works.
