### ISSUE TITLE
Unknown authentication strategy "login"

### ISSUE THREAD

**Issue by noisytoken** [EvanHahn/Express.js-in-Action-code#5]
After adding new user I am getting the following error 

```
Error: Unknown authentication strategy "login"
    at attempt (D:\express_learn\LAM\node_modules\passport\lib\middleware\authenticate.js:166:37)
    at authenticate (D:\express_learn\LAM\node_modules\passport\lib\middleware\authenticate.js:342:7)
    at Layer.handle [as handle_request] (D:\express_learn\LAM\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\express_learn\LAM\node_modules\express\lib\router\route.js:137:13)
    at D:\express_learn\LAM\node_modules\mongoose\lib\model.js:3800:16
    at D:\express_learn\LAM\node_modules\mongoose\lib\services\model\applyHooks.js:150:20
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```
Why is that ?

**Comment by EvanHahn** [comment]
This is a known error with early listings in Chapter 8. Could you continue through the chapter and see if you still have this error?

**Comment by noisytoken** [comment]
Today I tried again. It worked miraculously without any change.

One more thing you have omitted validation completely in you book. I have done some search and it seems to me, to generate the error in front-end I have to iterate through the error and then send it along with the response. Is there a package any package available to ease the process ?

**Comment by EvanHahn** [comment]
Do you mean validation for user inputs? If so, I think it depends a fair bit on the application.

**Comment by noisytoken** [comment]
Yes, I want to validate inputs . BTW Your book was a one of the best resources on Beginning Node JS I have ever read. I have one question though. Is it true that Node/express is only used to build REST apis ?

**Comment by EvanHahn** [comment]
No! Express can be used to build APIs, traditional web applications, and a whole lot more.

**Comment by EvanHahn** [comment]
I'm going to close this issue but feel free to open a new one if you are having problems.

**Comment by noisytoken** [comment]
Yes, please do so and thanks for answering my queries.

**Comment by ethanvo612** [comment]
I have this same problem, but I cannot fix it, could you help me, plz?

**Comment by EvanHahn** [comment]
@Sagit612 Please open a new issue with more information. I'm happy to help!
