### ISSUE TITLE
Body of guestbook entry doesn't appear in guestbook

### ISSUE THREAD

**Issue by mikeshhoffman** [EvanHahn/Express.js-in-Action-code#6]
In Express.js-in-Action-code/Chapter_03/guestbook/views/index.ejs
<%= entry.content %>
should be 
<%= entry.body %>
since app.js pushes the object member name "body" into the array of entries:
  entries.push({
    title: req.body.title,
    body: req.body.body,
Otherwise, the body of the guestbook entry isn't shown in the guestbook; only the title of the entry is shown.

**Comment by mikeshhoffman** [comment]
The printed book is correct, page 47.

**Comment by mikeshhoffman** [comment]
The important thing is that the two files need to use the same member-name.
Currently, the two files in the book are mismatched, and the two github files are mismatched in the reversed way:

Book: app.js (page 46) has "content:": content: request.body.body;
Book: index.ejs (page 47) instead has ".body": <%= entry.body %>

github: app.js has "body:": body: req.body.body,
github: index.ejs instead has ".content": <%= entry.content %>

**Comment by mikeshhoffman** [comment]
The Errata also contains the mismatch. Remove the errata item:
Page 47, Listing 3.23, "entry.body..."

 https://manning-content.s3.amazonaws.com/download/3/7dc447b-d272-402e-a56d-4ca68c80e97f/Hahn_express_in_action_err3.html

**Comment by EvanHahn** [comment]
I've had loads of issues with this. No chance you could open a pull request to make the code correct? If not, I can do it.

**Comment by mikeshhoffman** [comment]
https://github.com/EvanHahn/Express.js-in-Action-code/pull/7

**Comment by EvanHahn** [comment]
Thanks! I may not be able to take a look at this for a little bit, but I'll get to it in the next couple of weeks.

**Comment by EvanHahn** [comment]
Gonna close this issue now that #7 is closed. Thanks for your contributions!
